---
language: python # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.5 on Ubuntu 14.04"
      python: 3.5
      dist: trusty
    - name: "Python 3.6 on Ubuntu 14.04"
      python: 3.6
      dist: trusty
    - name: "Python 3.5 on Ubuntu 16.04"
      python: 3.5
      dist: xenial
    - name: "Python 3.6 on Ubuntu 16.04"
      python: 3.6
      dist: xenial
    - name: "Python 3.7 on Ubuntu 16.04"
      python: 3.7
      dist: xenial
    - name: "Python 3.8 on Ubuntu 16.04"
      python: 3.8
      dist: xenial
      before_install: sudo apt-get install libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libtiff5-dev libx11-6 libx11-dev fluid-soundfont-gm timgm6mb-soundfont xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic fontconfig fonts-freefont-ttf libfreetype6-dev
    - name: "Python 3.5 on Ubuntu 18.04"
      python: 3.5
      dist: bionic
    - name: "Python 3.6 on Ubuntu 18.04"
      python: 3.6
      dist: bionic
    - name: "Python 3.7 on Ubuntu 18.04"
      python: 3.7
      dist: bionic
    - name: "Python 3.8 on Ubuntu 18.04"
      python: 3.8
      dist: bionic
      before_install: sudo apt-get install libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libtiff5-dev libx11-6 libx11-dev fluid-soundfont-gm timgm6mb-soundfont xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic fontconfig fonts-freefont-ttf libfreetype6-dev
    - name: "Python 3.8 on macOS 10.14 (Xcode 10.2)"
      os: osx
      osx_image: xcode10.2
      language: shell
install:
  - pip3 install -r requirements.txt
script:
  - make
notifications:
  email: false
